=== trissz/CUNPO1WebKonyv/CUNPO1_0507/CUNPO1/2. Feladat/XMLSchemaCUNPO1.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

<xs:element name="BTK_orarend">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="ora" type="oraTipus" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:complexType name="oraTipus">
    <xs:sequence>
        <xs:element name="targy" type="xs:string"/>
        <xs:element name="idopont" type="idopontTipus" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="helyszin" type="xs:string"/>
        <xs:element name="oktato" type="xs:string"/>
        <xs:element name="szak" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:byte" use="required"/>
    <xs:attribute name="tipus" type="oraTipusTipus" default="Elmélet"/>
</xs:complexType>

<xs:complexType name="idopontTipus">
    <xs:sequence>
        <xs:element name="nap" type="napTipus"/>
        <xs:element name="tol" type="intervallumTipus"/>
        <xs:element name="ig" type="intervallumTipus"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="napTipus">
    <xs:restriction base="xs:string">
        <xs:enumeration value="hétfő"/>
        <xs:enumeration value="kedd"/>
        <xs:enumeration value="szerda"/>
        <xs:enumeration value="csütörtök"/>
        <xs:enumeration value="péntek"/>
        <xs:enumeration value="szombat"/>
        <xs:enumeration value="vasárnap"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="intervallumTipus">
    <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="8"/>
        <xs:maxInclusive value="18"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="oraTipusTipus">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Elmélet"/>
        <xs:enumeration value="Gyakorlat"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== trissz/CUNPO1WebKonyv/CUNPO1_0507/CUNPO1/2. Feladat/CUNPO1_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>

<BTK_orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaCUNPO1.xsd">
    <ora id="1" tipus="Elmélet">
        <targy>Valószínűségszámítás és statisztika</targy>
        <idopont>
            <nap>hétfő</nap>
            <tol>10</tol>
            <ig>14</ig>
        </idopont>
        <helyszin>Teológia Szemere utca 1/A</helyszin>
        <oktato>Alföldi Attila</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="2" tipus="Gyakorlat">
        <targy>Webkönyvtárak</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>12</tol>
            <ig>14</ig>
        </idopont>
        <helyszin>Teológia Szemere utca 1/A</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="3" tipus="Gyakorlat">
        <targy>Webkönyvtárak</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>16</tol>
            <ig>18</ig>
        </idopont>
        <helyszin>Teológia Szemere utca 1/A</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="4" tipus="Elmélet">
        <targy>Komputergrafika és képfeldolgozás</targy>
        <idopont>
            <nap>csütörtök</nap>
            <tol>12</tol>
            <ig>14</ig>
        </idopont>
        <helyszin>Teológia Szemere utca 1/A</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="5" tipus="Elmélet">
        <targy>Komputergrafika és képfeldolgozás</targy>
        <idopont>
            <nap>csütörtök</nap>
            <tol>16</tol>
            <ig>18</ig>
        </idopont>
        <helyszin>Teológia Szemere utca 1/A</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="6" tipus="Elmélet">
        <targy>Kalkulus</targy>
        <idopont>
            <nap>péntek</nap>
            <tol>13</tol>
            <ig>18</ig>
        </idopont>
        <helyszin>-</helyszin>
        <oktato>Wiersumné Dr. Gyöngyösi Erika</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="7" tipus="Elmélet">
        <targy>Operációs rendszerek</targy>
        <idopont>
            <nap>szombat</nap>
            <tol>9</tol>
            <ig>13</ig>
        </idopont>
        <helyszin>-</helyszin>
        <oktato>Janics Tamás</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
</BTK_orarend>
